# ═══════════════════════════════════════════════════════════════════════════════
# cross_validate.R — Cross-validate R rdtp against Stata rdtp
# ═══════════════════════════════════════════════════════════════════════════════
#
# This script generates a synthetic test dataset, runs rdtp in R, and
# compares the results against Stata's rdtp output. Because both
# implementations use parametric OLS (lm / regress), results should
# match to within floating-point precision.
#
# USAGE:
#   1. Run this script in R to generate test data and R results.
#   2. Open Stata and run the .do file this script creates.
#   3. Re-run this script to load Stata results and compare.
#
# REQUIRES: Stata installed and accessible (for the Stata step).
# NOT part of the testthat suite (run manually).
# ═══════════════════════════════════════════════════════════════════════════════

library(rdtp)

cat("\n=== Cross-Validation: R rdtp vs Stata rdtp ===\n\n")

# ─────────────────────────────────────────────────────────────────────────────
# 1. Generate synthetic test data
# ─────────────────────────────────────────────────────────────────────────────

set.seed(20260223)
n <- 500

dat <- data.frame(
    school     = rep(1:5, each = 100),
    test_score = 200 + sample(0:300, n, replace = TRUE)
)
true_cuts <- c(300, 350, 400, 325, 375)
dat$true_cutoff <- true_cuts[dat$school]
dat$above   <- as.integer(dat$test_score >= dat$true_cutoff)
dat$outcome <- 50 + 0.1 * dat$test_score + 20 * dat$above + rnorm(n, 0, 3)

# Save test data as CSV (readable by both R and Stata)
csv_path <- file.path(dirname(sys.frame(1)$ofile %||% "."),
                      "cross_validation_data.csv")
if (!file.exists(csv_path)) {
    csv_path <- "tests/cross-validation/cross_validation_data.csv"
}
write.csv(dat, file = csv_path, row.names = FALSE)
cat(sprintf("Test data saved to: %s\n", csv_path))

# ─────────────────────────────────────────────────────────────────────────────
# 2. Run rdtp in R
# ─────────────────────────────────────────────────────────────────────────────

fit_r <- rdtp(dat, depvar = "outcome", forcing = "test_score",
              by = "school", searchrange = c(250, 450), bandwidth = 75)

r_results <- fit_r$results
cat("\nR results:\n")
print(r_results)

# Save R results
r_results_path <- sub("data\\.csv$", "r_results.csv", csv_path)
write.csv(r_results, file = r_results_path, row.names = FALSE)
cat(sprintf("\nR results saved to: %s\n", r_results_path))

# ─────────────────────────────────────────────────────────────────────────────
# 3. Generate Stata .do file
# ─────────────────────────────────────────────────────────────────────────────

do_path <- sub("data\\.csv$", "run_stata.do", csv_path)
do_lines <- c(
    "* Auto-generated by cross_validate.R",
    "* Run this in Stata to produce Stata results for comparison",
    "",
    "clear all",
    "set more off",
    "",
    sprintf("import delimited \"%s\", clear",
            normalizePath(csv_path, mustWork = FALSE)),
    "",
    "* Run rdtp with the same parameters as R",
    "rdtp outcome test_score, by(school) searchrange(250 450) bandwidth(75)",
    "",
    "* Save results matrix to CSV",
    "matrix R = r(results)",
    "clear",
    "svmat double R, names(col)",
    "rename c1 cutoff",
    "rename c2 r2",
    "rename c3 beta",
    "rename c4 se",
    "rename c5 tstat",
    "rename c6 n_left",
    "rename c7 n_right",
    "rename c8 n_total",
    "rename c9 pred_left",
    "rename c10 pred_right",
    "gen school = _n",
    sprintf("export delimited \"%s\", replace",
            normalizePath(sub("data\\.csv$", "stata_results.csv", csv_path),
                          mustWork = FALSE)),
    "",
    "di \"Stata results saved.\""
)
writeLines(do_lines, do_path)
cat(sprintf("Stata .do file saved to: %s\n", do_path))

# ─────────────────────────────────────────────────────────────────────────────
# 4. Compare (if Stata results exist)
# ─────────────────────────────────────────────────────────────────────────────

stata_path <- sub("data\\.csv$", "stata_results.csv", csv_path)

if (file.exists(stata_path)) {
    cat("\n=== Comparing R vs Stata results ===\n\n")

    stata_results <- read.csv(stata_path)

    # Columns to compare (excluding unit, which is stored differently)
    compare_cols <- c("cutoff", "r2", "beta", "se", "tstat",
                      "n_left", "n_right", "n_total",
                      "pred_left", "pred_right")

    tol <- 1e-8
    all_match <- TRUE

    for (col in compare_cols) {
        r_vals     <- r_results[[col]]
        stata_vals <- stata_results[[col]]

        diffs <- abs(r_vals - stata_vals)
        max_diff <- max(diffs, na.rm = TRUE)

        if (max_diff > tol) {
            cat(sprintf("  MISMATCH: %s — max difference = %.2e\n",
                        col, max_diff))
            all_match <- FALSE
        } else {
            cat(sprintf("  OK: %s — max difference = %.2e\n",
                        col, max_diff))
        }
    }

    cat("\n")
    if (all_match) {
        cat("ALL COLUMNS MATCH within tolerance (1e-8)\n")
    } else {
        cat("SOME COLUMNS DO NOT MATCH — investigate discrepancies\n")
    }
} else {
    cat(sprintf(
        "\nStata results not found at: %s\n", stata_path))
    cat("Run the Stata .do file first, then re-run this script.\n")
}

cat("\n=== Done ===\n")
